import { HiOutlineComputerDesktop } from 'react-icons/hi2';
import { IoLogInSharp } from 'react-icons/io5';
import { BiReceipt } from 'react-icons/bi';
import { BsStopwatch } from 'react-icons/bs';
import { MdSupportAgent } from 'react-icons/md';
import { FaRegHandshake } from 'react-icons/fa';

const Solutions = () => {
  const blockContent = [
    {
      id: 1,
      icon: <HiOutlineComputerDesktop className='text-blue-1 text-60' />,
      title: 'Online Corporate Booking Tool and Mobile App ',
      text: `Perfect for booking flights, hotels and chauffeur driver cars all over the world`,
      delayAnim: '100',
    },
    {
      id: 2,
      icon: <IoLogInSharp className='text-blue-1 text-60' />,
      title: 'Automated Web Check-in',
      text: `For Domestic flights`,
      delayAnim: '200',
    },
    {
      id: 3,
      icon: <BsStopwatch className='text-blue-1 text-60' />,
      title: 'Daily Travel Schedule Reminders',
      text: `Super important when you double and triple book for flights`,
      delayAnim: '300',
    },
    {
      id: 4,
      icon: <BiReceipt className='text-blue-1 text-60' />,
      title: 'Automated Invoicing Mechanism',
      text: `All invoices are autogenerated and added to the running ledger the moment the travel is booked. All Invoices are GST Compliant and work seamlessly with most accounting systems`,
      delayAnim: '400',
    },
    {
      id: 5,
      icon: <MdSupportAgent className='text-blue-1 text-60' />,
      title: '24x7 Customer Service',
      text: `We know how critical your meetings are - and we also know how frequently plans change or get cancelled - Hence we have a dedicated support team to assist with these changes`,
      delayAnim: '500',
    },
    {
      id: 6,
      icon: <FaRegHandshake className='text-blue-1 text-60' />,
      title: 'A Single Point of Contact per corporate account',
      text: `When you sign up with us, a primary and single point of contact`,
      delayAnim: '600',
    },
  ];
  return (
    <>
      {blockContent.map((item) => (
        <div
          className='col-lg-4 col-sm-6'
          data-aos='fade'
          data-aos-delay={item.delayAnim}
          key={item.id}
        >
          <div className='featureIcon -type-1 '>
            <div className='row justify-center'>{item.icon}</div>
            <div className='text-center mt-30'>
              <h4 className='text-18 fw-500'>{item.title}</h4>
              <p className='text-15 mt-10 px-10'>{item.text}</p>
            </div>
          </div>
        </div>
      ))}
    </>
  );
};

export default Solutions;
