import { BiReceipt } from 'react-icons/bi';
import { BsStopwatch } from 'react-icons/bs';
import { FaRegHandshake } from 'react-icons/fa';
import { HiOutlineComputerDesktop } from 'react-icons/hi2';
import { IoLogInSharp } from 'react-icons/io5';
import { MdSupportAgent } from 'react-icons/md';

function ContactGetStarted () {
  const cards = [
    {
      icon: <HiOutlineComputerDesktop className='text-blue-1 icon' />,
      title: 'Corporate Booking Tool',
      subtitle:
        'Our online corporate booking tool is perfect for booking flights, hotels, and chauffeur driver cars all over the world. With a user-friendly interface and easy navigation, you can book your travel arrangements hassle-free. Our advanced technology ensures that you get the best prices available in the market, saving you both time and money.',
      points: [
        'Lorem ipsum dolor sit amet, consectetur adi piscing elit, sed do eiusmod',
        'Lorem ipsum dolor sit amet, consectetur adi piscing elit, sed do eiusmod',
        'Lorem ipsum dolor sit amet, consectetur adi piscing elit, sed do eiusmod',
      ],
      knowMoreLink: '#',
    },
    {
      icon: <IoLogInSharp className='text-blue-1 icon' />,
      title: 'Automated Web Check-in',
      subtitle:
        "We understand the importance of convenience and time management when it comes to corporate travel. That's why we offer an automated web check-in service for domestic flights. This service saves you time by eliminating the need for manual check-ins and ensures that you are always on time for your flight.",
      points: [
        'Lorem ipsum dolor sit amet, consectetur adi piscing elit, sed do eiusmod',
        'Lorem ipsum dolor sit amet, consectetur adi piscing elit, sed do eiusmod',
        'Lorem ipsum dolor sit amet, consectetur adi piscing elit, sed do eiusmod',
      ],
      knowMoreLink: '#',
    },
    {
      icon: <BsStopwatch className='text-blue-1 icon' />,
      title: 'Daily Travel Schedule Reminders',
      subtitle:
        'Keeping track of your travel schedule can be a daunting task, especially when you have multiple flights to catch. Our daily travel schedule reminders alert you for schedule clashes and even when to cancel flights to avoid no-shows. With these reminders, you will never miss a flight or an important meeting, ensuring that your travel plans go smoothly.',
      points: [
        'Lorem ipsum dolor sit amet, consectetur adi piscing elit, sed do eiusmod',
        'Lorem ipsum dolor sit amet, consectetur adi piscing elit, sed do eiusmod',
        'Lorem ipsum dolor sit amet, consectetur adi piscing elit, sed do eiusmod',
      ],
      knowMoreLink: '#',
    },
    {
      icon: <BiReceipt className='text-blue-1 icon' />,
      title: 'Automated Invoicing Mechanism',
      subtitle:
        'Our automated invoicing mechanism ensures that all invoices are autogenerated and added to the running ledger the moment the travel is booked. All invoices are GST compliant and work seamlessly with most accounting systems. With this system, you can easily keep track of your travel expenses and manage your finances effectively.',
      points: [
        'Lorem ipsum dolor sit amet, consectetur adi piscing elit, sed do eiusmod',
        'Lorem ipsum dolor sit amet, consectetur adi piscing elit, sed do eiusmod',
        'Lorem ipsum dolor sit amet, consectetur adi piscing elit, sed do eiusmod',
      ],
      knowMoreLink: '#',
    },
    {
      icon: <MdSupportAgent className='text-blue-1 icon' />,
      title: '24x7 Customer Service',
      subtitle:
        "We understand that your meetings are critical, and plans can change or get cancelled frequently. That's why we have a dedicated support team available 24x7 to assist with any changes or issues you may encounter during your travel. Our team is always ready to assist you and ensure that your travel plans go smoothly.",
      points: [
        'Lorem ipsum dolor sit amet, consectetur adi piscing elit, sed do eiusmod',
        'Lorem ipsum dolor sit amet, consectetur adi piscing elit, sed do eiusmod',
        'Lorem ipsum dolor sit amet, consectetur adi piscing elit, sed do eiusmod',
      ],
      knowMoreLink: '#',
    },
    {
      icon: <FaRegHandshake className='text-blue-1 icon' />,
      title: 'Single Point of Contact',
      subtitle:
        'We believe in providing our clients with the best possible service. When you sign up with us, you will have a primary and single point of contact for your corporate account. This ensures that all your travel arrangements are handled professionally and efficiently, providing you with a stress-free travel experience.',
      points: [
        'Lorem ipsum dolor sit amet, consectetur adi piscing elit, sed do eiusmod',
        'Lorem ipsum dolor sit amet, consectetur adi piscing elit, sed do eiusmod',
        'Lorem ipsum dolor sit amet, consectetur adi piscing elit, sed do eiusmod',
      ],
      knowMoreLink: '#',
    },
  ];

  const features = [
    {
      title: 'Create Your Account Now',
      subtitle:
        'Get started by providing minimal details like employee size, organisation name, etc.',
    },
    {
      title: 'Set Up Employee-friendly Policy Guidelines',
      subtitle:
        'Gain most of the benefits by setting up employee-friendly policies (only Admin users).',
    },
    {
      title: 'Invite Your Employees & Start Booking',
      subtitle:
        'Invite your employees to myBiz so that they could enjoy all the corporate benefits.',
    },
  ];

  return (
    <div id='contact-started'>
      <div className='section-bg layout-pt-lg bg-light started-title'>
        <div className='container'>
          <div className='col-lg-6 pr-20 lg:pr-0'>
            <h1 className='text-light-4'>Our Technologies</h1>
            {/* <h5 className='mt-20 text-light-4'>
              Our features and benefits are curated to suit the needs of every employee
              using myBiz.
            </h5> */}
          </div>
        </div>
      </div>
      <div className='section-bg main-container'>
        <div className='container'>
          {/* Cards */}
          <div className='row x-gap-30 y-gap-30 cards-container'>
            {cards.map((element, index) => (
              <div key={index} className='col-lg-4'>
                <div key={index} className='px-30 py-40 bg-white contact-card'>
                  <div className='mb-20 mt-10'>{element.icon}</div>
                  <h2>{element.title}</h2>
                  <span className='mt-10 d-block text-14'>{element.subtitle}</span>
                  {/* {element.points.map((point, pointIndex) => (
                    <span
                      className='d-flex gap-2 text-light-4 points mt-30'
                      key={pointIndex}
                    >
                      <span className='text-blue-1'>
                        <AiFillStar />
                      </span>
                      <span>{point}</span>
                    </span>
                  ))}
                  <a
                    className='text-center d-block text-16 text-blue-1 mt-40 fw-700'
                    href={element.knowMoreLink}
                  >
                    KNOW MORE
                  </a> */}
                </div>
              </div>
            ))}
          </div>
          {/* <div className='col-lg-6 mt-80 col-12'>
            <h3 className='text-light-4 mb-10'>
              Grab all the corporate benefits by creating your account now
            </h3>
            <div className='d-inline-block started-button col-12 pr-40 lg:pr-0 mt-20'>
              <Link
                href='/hotel/hotel-list-v5'
                className='button py-20 col-12 text-18 text-center bg-blue-1 text-white'
              >
                Find Deals
              </Link>
            </div>
          </div> */}
          {/* Features */}
          {/* <div className='features'>
            <h1 className='fw-500 col-lg-8'>
              No Waiting, No Subscription Charges, Get Started Instantly!
            </h1>
            <div className='row mt-45 x-gap-60 y-gap-30'>
              {features.map((element, index) => (
                <div className='feature col-lg-4'>
                  <span className='text-40 fw-700 text-white feature-number'>
                    {index + 1}
                  </span>
                  <h2 className='text-dark-2 mt-30'>{element.title}</h2>
                  <h5 className='text-light-4 fw-200 mt-20'>{element.subtitle}</h5>
                </div>
              ))}
            </div>
            <div className='d-inline-block started-button col-lg-3 col-12 pr-40 lg:pr-0 mt-60'>
              <Link
                href='/hotel/hotel-list-v5'
                className='button py-10 col-lg-11 col-12 text-18 text-center bg-blue-1 text-white'
              >
                Create Now
              </Link>
            </div>
          </div> */}
        </div>
      </div>
    </div>
  );
}

export default ContactGetStarted;
