export const airlineMealOptions = {
  QP: {
    CNCC: 'Croissants - QP Chicken Club Croissant',
    CVMC: 'Croissants - Mushroom & brie Croissant',
    CVCB: 'Appetizers - Chaat-buster Box',
    CNKP: 'Appetizers - Kari Pan-tastic Chicken Pocket',
    CVTT: 'Kids Meal - Triple Treat Nutella Sandwich',
    CVPP: 'Sandwich - Peppy Paneer Sandwich',
    CNCS: 'Sandwich - Chicken & Cheese Sandwich',
    CNPC: 'Sandwich - Care-free-al Poi',
    CNKW: 'Wraps - Kosha Chicken Malabari Wrapper',
    CVKD: 'Burgers - Top Bun',
    CVFF: 'Salads - Fruit & Feta Fiesta Salad',
    CVLB: 'Salads - Lean Bean Protein Salad',
    CNSS: 'Salads - Chick-a-licious Salad',
    CNSA: 'Salads - Chicken Shawarma Salad',
    CDCP: 'Desserts - Chocolate Pistachio Verrine ',
    CNKS: 'Ready To Eat - WOW! Khow Suey Chicken',
    CNCR: 'Ready To Eat - Instabites Chicken Curry Rice',
    CVBY: 'Ready To Eat - MOM Veg Fried Rice',
    CUPM: 'Ready To Eat - MOM Rava Upma',
    CPOH: 'Ready To Eat - MOM Poha',
    CPAS: 'Ready To Eat - Tomato Cheese Pasta',
    CVNO: 'Ready To Eat - Veg Cup Noodles',
    CNNO: 'Ready To Eat - Chicken Cup Noodles',
    CVHB: 'Ready To Eat - Hyderabadi Veg Biryani',
    CBHL: 'Ready To Eat - Bhel Puri (Jain Special)',
    CCAS: 'Refreshments - Roasted Cashews',
    CALM: 'Refreshments - Mixed nuts',
    CPOP: 'Refreshments - Popcorn',
    CWAF: 'Refreshments - Wafers',
    CMAK: 'Refreshments - Makhana',
    CCOO: 'Refreshments - Cookie',
  },
  IX: {
    VIVF: 'Hot Meal (Veg) - Mini Idlis Medu Vada And Upma',
    VHNF: 'Hot Meal (Veg) - Hakka Noodles With Veg Manchurian',
    VMFF: 'Hot Meal (Veg) - Vegetable Manchurian With Fried Rice',
    VPDF: 'Hot Meal (Veg) - Paneer Makhani, Dal Tadka And Jeera Rice',
    VPMF: 'Hot Meal (Veg) - Paneer Makhani With Jeera Aloo & Vegetable Pulao',
    NCBF: 'Hot Meal (Non-Veg) - Awadhi Chicken Biryani With Mirch Salan',
    NCOF: 'Hot Meal (Non-Veg) - Cheddar Chives Omelette',
    NKPF: 'Hot Meal (Non-Veg) - Kebab Platter',
    VBSF: 'Lite Bite (Veg) - Barley Salad',
    VFPF: 'Lite Bite (Veg) - Seasonal Fresh Fruit Platter',
    VFSF: 'Lite Bite (Veg) - Feta Vegetable Salad With Vinaigrette',
    VHRF: 'Lite Bite (Veg) - Herb Roast Vegetable Roll',
    VQSF: 'Lite Bite (Veg) - Quinoa Salad',
    NCJF: 'Lite Bite (Non-Veg) - Chicken Junglee Sandwich',
    VSDF: 'Dessert (Veg) - Shôndesh Tiramisù',
    TMAF: 'Hot Beverage - Masala Tea',
    CFMF: 'Hot Beverage - Black Coffee',
  },
  '6E': {
    VGML: 'Veg Meal',
    NVML: 'Non-Veg Meal',
    CPML: 'Corporate Meal',
    TCSW: 'Tomato Cucumber Cheese Lettuce Sandwich Combo',
    PTSW: 'Paneer Tikka Sandwich Combo',
    CJSW: 'Chicken Tikka Sandwich Combo',
    CTSW: 'Chicken Junglee Sandwich Combo',
    POHA: 'Poha Combo',
    UPMA: 'Rava Upma Combo',
    SACH: 'Sambar Chawal Combo',
    VBIR: 'Veg Biryani Combo',
    DACH: 'Dal Chawal Combo',
    SCSW: 'Spinach Corn Sandwich',
    LVWR: 'Lucknowi Veg Wrap',
    CHPS: 'Chicken Pesto Sandwich',
    APWR: 'Achari Paneer Tikka Wrap',
    MMPA: 'Murg Ka Mokul Wrap',
    SAMS: 'Samosa',
    BCCS: 'Banana Chips Classic Salt',
    CNWT: 'Cashew (Salted) 50 Gms',
    CCWT: 'Unibic Chocolate Chips Cookies - 50 Gm',
    CTAT: 'Chicken Tikka S/W-90 Gms',
    CLAT: 'Cucumber Cheese Lettuce Sandwich-90gms',
    CHFR: 'Chinese Fried Rice',
    CHCH: 'Chole Chawal',
    MASP: 'Makhana Salt And Pepper',
    SMAL: 'Smoked Almonds',
    CKKU: 'Chicken Keema With Kulcha',
    CHFS: 'Chicken And Feta Salad',
    CNKR: 'Chana Kulcha Roll',
    BHPS: 'Bhatti Paneer Salad',
    NUSW: '6E Eats Choice Of The Day (Non-Veg) + Beverage',
    VCSW: '6E Eats Choice Of The Day (Veg) + Beverage',
    AGSW: '#Indiabyindigo Regional Favourite (Veg) + Beverage',    
  },
};

export const getMealOptions = (airlineCode) => {
  const options = airlineMealOptions[airlineCode] || {};
  return Object.entries(options).map(([value, label]) => ({ value, label }));
};
